name: Get Tag
description: |
  This action parses the git-tree and returns the all git-tags in the tree.
  As it is more likely that only the newest tag is needed, this action can be configured to only return the newest tag.
author: Martin Weissbach
outputs:
  tag:
    description: |
      The parsed git-tag is returned.
      If no tag is found, the output will be empty.
  tags:
    description: |
      An array of all found git-tags in the git-tree are returned.
      This output will only contain values if `newest_tag_only` is set to
      `false` and will be empty otherwise.
inputs:
  newest_tag_only:
    description: |
      If this flag is set to `true` only the newest git-tag is returned.
      Otherwise all tags are returned.
    required: false
    default: 'true'
runs:
  using: 'node16'
  main: 'dist/index.js'
