name: Get Tag
description: Get the git tag from the GITHUB_REF environment variable.
author: Martin Weissbach
outputs:
  tag:
    description: the git tag name
runs:
  using: 'node16'
  main: 'dist/index.js'
