name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js from .nvmrc
        uses: actions/setup-node@v4.0.4
        with:
          node-version-file: '.nvmrc'

      - run: |
          npm install

      - run: |
          npm run all
